export const ErrorCodes = {
  COMMON_BAD_REQUEST: 'COMMON_BAD_REQUEST',
  COMMON_UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  COMMON_FORBIDDEN: 'COMMON_FORBIDDEN',
  COMMON_NOT_FOUND: 'COMMON_NOT_FOUND',
  COMMON_CONFLICT: 'COMMON_CONFLICT',
  COMMON_INTERNAL_ERROR: 'COMMON_INTERNAL_ERROR',

  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',

  PARKING_SPACE_NOT_FOUND: 'PARKING_SPACE_NOT_FOUND',
  PARKING_SPACE_NOT_OCCUPIED: 'PARKING_SPACE_NOT_OCCUPIED',
  PARKING_SESSION_NOT_FOUND: 'PARKING_SESSION_NOT_FOUND',
  PARKING_SESSION_ALREADY_REGISTERED: 'PARKING_SESSION_ALREADY_REGISTERED',

  VISITOR_NOT_FOUND: 'VISITOR_NOT_FOUND',
  VISITOR_INVALID_PIN: 'VISITOR_INVALID_PIN',

  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',

  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_FAULT_NOT_FOUND: 'DEVICE_FAULT_NOT_FOUND',
} as const;